// Wifi
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// OTA
#define OTA_PASSWORD "YOUR_OTA_UPDATE_PASSWORD"

// MQTT
#define MQTT_USERNAME "YOUR_MQTT_USERNAME"
#define MQTT_PASSWORD "YOUR_MQTT_PASSWORD"

// Web server
#define WWW_USERNAME "YOUR_WEB_SERVER_USERNAME"
#define WWW_PASSWORD "YOUR_WEB_SERVER_PASSWORD"
